image: docker:28.4.0

stages:
  - lint-app
  - build
  - test
  - prepare
  - deploy
  - rollback
  - notify

variables:
  REGISTRY: https://index.docker.io/v1/
  DOCKER_REPO: ivankhodyrev/bookstore-app
  DOCKER_USER: ivankhodyrev
  SSH_OPT: -o StrictHostKeyChecking=no
  SSH_USER: gitlab-runner
  PRJ_DIR: /var/www/bookstore-app
  GIT_URL: https://gitlab.com/khodyrev-ivan/diplom.git
  API_URL: https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage
  TIMEOUT: 5
  IMAGE_TAG: ${DOCKER_REPO}:${CI_PIPELINE_ID}
  DB_USER: bookstoreuser
  DB_NAME: bookstore
  DB_HOST: bookstore-db

linter-app:job:
  stage: lint-app
  image: python:3.12-slim
  before_script:
    - pip install pylint
  script:
    - pylint ./app/*.py
  rules:
    - if: '$MODE == "deploy"'
  allow_failure: true
  tags:
    - runner

linter-docker:job:
  stage: lint-app
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint Dockerfile
  rules:
    - if: '$MODE == "deploy"'
  allow_failure: true
  tags:
    - runner

build:job:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"$DOCKER_USER\",\"password\":\"$DOCKER_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context=$CI_PROJECT_DIR --dockerfile=$CI_PROJECT_DIR/Dockerfile --destination=${IMAGE_TAG}
  rules:
    - if: '$MODE == "deploy"'
  tags:
    - runner

test:job:
  stage: test
  needs: 
    - job: build:job
      optional: true 
  image: 
    name: ${IMAGE_TAG}
    entrypoint: [""] 
  variables:
    POSTGRES_DB: mydb
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ${DB_PASS_TST}
    POSTGRES_AUTH_METHOD: trust
  services:
    - name: postgres:16
      alias: db
  before_script:
    - pip install -r ./app/requirements.txt
  script:
    - pytest -v --disable-warnings --maxfail=1 ./app/tests_app.py | tee bookstore-tests_${CI_PIPELINE_ID}.log
  rules:
    - if: '$MODE == "deploy"'
  artifacts:
    paths:
      - bookstore-tests_${CI_PIPELINE_ID}.log
  tags:
    - runner

prepare:job:
  stage: prepare
  extends: .ssh_setup
  before_script:
    - export HOST=$(cat terraform/instance_ip.txt)
  script:
    - |
      ssh ${SSH_USER}@${HOST} "
        test -d /var/www || sudo mkdir -p /var/www;
        sudo chown -R gitlab-runner:gitlab-runner /var/www;
        test -d ${PRJ_DIR} || git clone ${GIT_URL} ${PRJ_DIR};
        cd ${PRJ_DIR};
        git checkout main;
        git pull;
        touch .env;
        sed -i '/^APP_IMAGE=/d' .env ;
        echo "APP_IMAGE=${IMAGE_TAG}" >> .env ;
        grep -q '^DB_PASS=' .env || echo "DB_PASS=${DB_PASS}" >> .env ;
        grep -q '^DB_USER=' .env || echo "DB_USER=${DB_USER}" >> .env ;
        grep -q '^DB_NAME=' .env || echo "DB_NAME=${DB_NAME}" >> .env ;
        grep -q '^DB_HOST=' .env || echo "DB_HOST=${DB_HOST}" >> .env ;
      "
  rules:
    - if: '$MODE == "deploy"'
  tags:
    - runner

deploy-compose:job:
  stage: deploy
  needs: 
    - job: prepare:job
      optional: true
  extends: .ssh_setup
  before_script:
    - export HOST=$(cat terraform/instance_ip.txt)
  script:
    - |
      ssh ${SSH_USER}@${HOST} "cd ${PRJ_DIR}; 
      sudo docker compose pull;
      sudo docker compose up -d"
  rules:
    - if: '$MODE == "deploy"'
      when: manual
  tags:
    - runner

rollback:job:
  stage: rollback
  extends: .ssh_setup
  before_script:
    - export HOST=$(cat terraform/instance_ip.txt)
  script:
    - |
      ssh ${SSH_USER}@${HOST} "
        if [ -z "${TAG}" ]; then
          echo "TAG is missing. Usage: TAG for rollback"
          exit
        fi
        cd ${PRJ_DIR}; 
        test -f .env || touch .env
        sed -i '/^APP_IMAGE=/d' .env
        echo -e \"\nAPP_IMAGE=${DOCKER_REPO}:${TAG}\" >> .env
        docker compose up -d --force-recreate
      "
  rules:
    - if: '$MODE == "rollback"'
      when: manual
    - when: never
  tags:
    - runner

telegram_notify_success:job:
  stage: notify
  image: curlimages/curl
  before_script: |
    export URL=${API_URL}
    if [ "$MODE" == "rollback" ]; then
      export MODE="Rollback"
      export VERSION="${DOCKER_REPO}:${TAG}"
      export EMOJI="⬅️"
    else
      export MODE="Deploy"
      export VERSION="${IMAGE_TAG}"
      export EMOJI="✅"
    fi
    
    export TEXT="${EMOJI} ${MODE} for ${CI_PROJECT_NAME} by ${GITLAB_USER_NAME}%0AVersion: ${VERSION}%0APipeline: ${CI_PIPELINE_URL}"
  script:
    - |
      curl -s -X POST ${URL} \
        -d chat_id=${TELEGRAM_CHAT_ID} \
        -d text="${TEXT}" \
        -d parse_mode=Markdown
  when: on_success
  rules:
    - if: '$MODE == "deploy"'
    - if: '$MODE == "rollback"'
  tags:
    - runner

telegram_notify_failure:job:
  stage: notify
  image: curlimages/curl
  before_script: |
    export URL=${API_URL}
    if [ "$MODE" == "rollback" ]; then
      export MODE="Rollback"
      export EMOJI="❌"
    else
      export MODE="Build"
      export EMOJI="❌"
    fi
    
    export TEXT="${EMOJI} ${MODE} for ${CI_PROJECT_NAME} by ${GITLAB_USER_NAME} failed on branch *${CI_COMMIT_BRANCH}*:%0AJob: ${CI_JOB_NAME}%0APipeline: ${CI_PIPELINE_URL}"
  script:
    - |
      curl -s -X POST ${URL} \
        -d chat_id=${TELEGRAM_CHAT_ID} \
        -d text="${TEXT}" \
  when: on_failure
  rules:
    - if: '$MODE == "deploy"'
    - if: '$MODE == "rollback"'
  tags:
    - runner