def remote = [:]
pipeline {
    agent {
        label 'docker'
    }

    parameters {
        gitParameter(
            type: 'PT_BRANCH', 
            name: 'BRANCH', 
            branchFilter: 'origin/.*', 
            sortMode: 'DESCENDING_SMART',
            defaultValue: 'main',
            quickFilterEnabled: true
        )
        string(
            name: 'HOST',
            defaultValue: '192.168.56.9',
            description: 'Host for deploy'
        )
        booleanParam(
            name: 'ROLLBACK',
            defaultValue: false,
            description: 'Откатить на версию $TAG'
        )
        booleanParam(
            name: 'RUN_TEST',
            defaultValue: true,
            description: 'Запуск тестов'
        )
        string(
            name: 'TAG',
            defaultValue: '',
            description: 'Тэг (:bookstore-1) для rollback'
        )
    }
    environment {
        DOCKER_REPO = 'ivankhodyrev/bookstore-app'
        DOCKER_TOKEN = credentials('docker_token')
        REPO_USER = 'ivan'
        GIT_URL = 'git@github.com:ioannsnakej/diplom.git'
        PRJ_DIR = '/var/www/bookstore-app'
        DB_USER="bookstore-user"
        DB_NAME="bookstore-db"
        DB_HOST="db"
    }

    stages {
        stage('Configure credentials'){
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'jenkins-key', keyFileVariable: 'private_key', usernameVariable: 'username')]) {
                    script {
                        remote.name = "${params.HOST}"
                        remote.host = "${params.HOST}"
                        remote.user = "${username}"
                        remote.identity = readFile "${private_key}"
                        remote.allowAnyHosts = true
                    }
                }
            }
        }

        stage('Checkout repo'){
            steps {
                sshCommand remote: remote, command: """
                    set -ex; set -o pipefail
                    sudo mkdir -p /var/www
                    sudo chown -R jenkins:jenkins /var/www
                    test -d ${env.PRJ_DIR} || git clone ${env.GIT_URL} ${env.PRJ_DIR}
                    cd ${env.PRJ_DIR}
                    git checkout ${params.BRANCH}
                    git pull
                """
            }
        }

        stage('Build image') {
            when {
                expression { params.RUN_TEST && !params.ROLLBACK }
            }
            steps {
                sh """
                    docker build -t ${env.DOCKER_REPO}:${BUILD_NUMBER} .
                """
            }
        }

        stage('Push image'){
            when {
                expression { !params.ROLLBACK }
            }
            steps {
                sh """
                    docker login -u ${env.REPO_USER} -p ${env.DOCKER_TOKEN}
                    docker push ${env.DOCKER_REPO}:${BUILD_NUMBER}
                    docker logout
                """
            }
        }

        stage('Run tests'){
            when {
                expression { !params.ROLLBACK }
            }
            steps {
                warnError('Test failed'){
                    sh """
                        set -e
                        docker rm -f \$(docker ps -a -q) || true
                        docker network create tests
                        docker run -d --name db \
                            -e POSTGRES_USER=postgres \
                            -e POSTGRES_PASSWORD=postgres \
                            -e POSTGRES_DB=mydb \
                            --network=tests \
                            postgres:16
                        echo "Waiting for db.."
                        sleep 15
                        docker exec db psql -U postgres -d mydb -c "
                            CREATE TABLE IF NOT EXISTS books (
                                id SERIAL PRIMARY KEY,
                                title VARCHAR(200) NOT NULL,
                                author VARCHAR(100) NOT NULL,
                                price DECIMAL(10,2) NOT NULL,
                                count INTEGER DEFAULT 0
                            );
                        "
                        docker run -d --name backend \
                            -e DB_USER=postgres \
                            -e DB_PASS=postgres \
                            -e DB_NAME=mydb \
                            -e DB_HOST=db \
                            --network=tests \
                            ${env.DOCKER_REPO}:${BUILD_NUMBER}
                        sleep 10
                        docker exec backend python -m pytest tests_app.py -v --disable-warnings --maxfail=1
                    """
                }
            }
        }

        stage('Prepare envs'){
            when {
                expression { !params.ROLLBACK }
            }
            steps {
                sshCommand remote: remote, command: """
                    set -ex; set -o pipefail
                    cd ${env.PRJ_DIR}
                    if [ -f .env ] && grep 'DB_PASS' .env; then
                        DB_PASS=\$(grep 'DB_PASS' .env | cut -d= -f2 | tr -d '\"')
                    else
                        DB_PASS=\$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c12)
                    fi
                    cat > .env << EOF
                    APP_IMAGE=${env.DOCKER_REPO}:${BUILD_NUMBER}
                    DB_USER=${env.DB_USER}
                    DB_NAME=${env.DB_NAME}
                    DB_HOST=${env.DB_HOST}
                    DB_PASS=\${DB_PASS}
                    EOF
                    echo "✅ .env is ready"
                """
            }
        }

        stage('Deploy'){
            when {
                expression { !params.ROLLBACK }
            }
            steps {
                sshCommand remote: remote, command: """
                    set -ex; set -o pipefail
                    cd ${env.PRJ_DIR}
                    docker compose up -d
                """
            }
        }

        stage('Rollback'){
            when {
                expression { params.ROLLBACK == true }
            }
            steps {
                sshCommand remote: remote, command: """
                    set -ex; set -o pipefail
                    cd ${env.PRJ_DIR}
                    test -f .env || touch .env
                    sed -i '/APP_IMAGE=/d' .env
                    echo "APP_IMAGE="${env.DOCKER_REPO}:${env.TAG}" >> .env
                    docker compose up -d backend --force-recreate
                """
            }
        }
    }
}